In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv
/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv


In [2]:
dftrain=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv')
dftrain=dftrain.sample(frac=1)
dfeval=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv')

In [3]:
print(dftrain.head())
print(dfeval.head())

      gender   age  hypertension  heart_disease ever_married work_type  \
3896  Female  35.0             0              0          Yes   Private   
2578  Female   6.0             0              0           No  children   
4534  Female  61.0             0              0          Yes   Private   
902     Male  50.0             0              0          Yes   Private   
4275  Female  51.0             0              0          Yes  Govt_job   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
3896          Rural             119.40  22.9     never smoked       0  
2578          Rural              84.10  19.8          Unknown       0  
4534          Urban             129.31  30.7  formerly smoked       0  
902           Urban              57.93  27.6          Unknown       0  
4275          Urban              95.33  27.9     never smoked       0  
   gender   age  hypertension  heart_disease ever_married      work_type  \
0  Female  61.0             0              0   

In [4]:
y_train=dftrain.pop('stroke')
y_eval=dfeval.pop('stroke')

In [5]:
dftrain.loc[dftrain['gender']=='Male','gender']=1
dftrain.loc[dftrain['gender']=='Female','gender']=0
dftrain.loc[dftrain['ever_married']=='Yes','ever_married']=1
dftrain.loc[dftrain['ever_married']=='No','ever_married']=0
dftrain['Private'] = np.where(dftrain['work_type']== 'Private',1, 0)
dftrain['Self-employed'] = np.where(dftrain['work_type']== 'Self-employed',1, 0)
dftrain['Govt_job'] = np.where(dftrain['work_type']== 'Govt_job',1, 0)
dftrain['children'] = np.where(dftrain['work_type']== 'children',1, 0)
# dftrain.loc[dftrain['work_type']=='Private','work_type']=0
# dftrain.loc[dftrain['work_type']=='Self-employed','work_type']=1
# dftrain.loc[dftrain['work_type']=='Govt_job','work_type']=2
# dftrain.loc[dftrain['work_type']=='children','work_type']=3
dftrain.pop('work_type')
dftrain.loc[dftrain['Residence_type']=='Urban','Residence_type']=1
dftrain.loc[dftrain['Residence_type']=='Rural','Residence_type']=0
dftrain.loc[dftrain['smoking_status']=='formerly smoked','smoking_status']=1
dftrain.loc[dftrain['smoking_status']=='never smoked','smoking_status']=-1
dftrain.loc[dftrain['smoking_status']=='smokes','smoking_status']=2
dftrain.loc[dftrain['smoking_status']=='Unknown','smoking_status']=0
dftrain['age']=dftrain['age']/100
dftrain['avg_glucose_level']=dftrain['avg_glucose_level']/300
dftrain['bmi']=dftrain['bmi']/50
#dftrain['work_type']=dftrain['work_type']/3
dftrain['smoking_status']=dftrain['smoking_status']/3
dfeval.loc[dfeval['gender']=='Male','gender']=1
dfeval.loc[dfeval['gender']=='Female','gender']=0
dfeval.loc[dfeval['ever_married']=='Yes','ever_married']=1
dfeval.loc[dfeval['ever_married']=='No','ever_married']=0
dfeval['Private'] = np.where(dfeval['work_type']== 'Private',1, 0)
dfeval['Self-employed'] = np.where(dfeval['work_type']== 'Self-employed',1, 0)
dfeval['Govt_job'] = np.where(dfeval['work_type']== 'Govt_job',1, 0)
dfeval['children'] = np.where(dfeval['work_type']== 'children',1, 0)
# dfeval.loc[dfeval['work_type']=='Private','work_type']=0
# dfeval.loc[dfeval['work_type']=='Self-employed','work_type']=1
# dfeval.loc[dfeval['work_type']=='Govt_job','work_type']=2
# dfeval.loc[dfeval['work_type']=='children','work_type']=3
dfeval.pop('work_type')
dfeval.loc[dfeval['Residence_type']=='Urban','Residence_type']=1
dfeval.loc[dfeval['Residence_type']=='Rural','Residence_type']=0
dfeval.loc[dfeval['smoking_status']=='formerly smoked','smoking_status']=1
dfeval.loc[dfeval['smoking_status']=='never smoked','smoking_status']=-1
dfeval.loc[dfeval['smoking_status']=='smokes','smoking_status']=2
dfeval.loc[dfeval['smoking_status']=='Unknown','smoking_status']=0
dfeval['age']=dfeval['age']/100
dfeval['avg_glucose_level']=dfeval['avg_glucose_level']/300
dfeval['bmi']=dfeval['bmi']/50
#dfeval['work_type']=dfeval['work_type']/3
dfeval['smoking_status']=dfeval['smoking_status']/3

In [6]:
print(dftrain.head(50))
print(dfeval.head(50))

     gender     age  hypertension  heart_disease ever_married Residence_type  \
3896      0  0.3500             0              0            1              0   
2578      0  0.0600             0              0            0              0   
4534      0  0.6100             0              0            1              1   
902       1  0.5000             0              0            1              1   
4275      0  0.5100             0              0            1              1   
2843      0  0.2400             0              0            0              1   
3105      1  0.8000             0              0            1              1   
1447      0  0.2400             0              0            0              1   
3800      1  0.0400             0              0            0              1   
1327      1  0.5300             0              0            1              1   
1398      0  0.8200             0              0            1              0   
4225      1  0.8200             0       

In [7]:
train=dftrain.to_numpy()
evaluate=dfeval.to_numpy()
y_train=y_train.to_numpy().reshape((1,train.shape[0]))
y_eval=y_eval.to_numpy()
print(y_train.shape)

(1, 4981)


In [8]:
print(train)

[[0 0.35 0 ... 0 0 0]
 [0 0.06 0 ... 0 0 1]
 [0 0.61 0 ... 0 0 0]
 ...
 [1 0.18 0 ... 0 0 0]
 [1 0.71 0 ... 0 0 0]
 [1 0.38 0 ... 0 0 0]]


In [9]:
X=train.T
X=np.array(X,dtype=np.float64)
X_eval=evaluate.T
X_eval=np.array(X_eval,dtype=np.float64)

In [10]:
m=X.shape[1]
n_x=X.shape[0]

In [11]:
print(m)

4981


In [12]:
W=np.random.randn(1,n_x)*0.01
b=np.zeros((1,1))

In [13]:
print(W)
print(b)

[[-5.00574052e-03  5.99170643e-03 -8.40536168e-03  8.17318479e-03
  -1.96485066e-05  7.48338967e-03 -9.50797108e-03  3.32632994e-03
   5.62643397e-03  1.10840625e-02 -1.56292975e-03  1.36017064e-03
  -1.82453833e-02]]
[[0.]]


In [14]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [15]:
def cost_fn(X,W,b,m,y_train,lamda):
    Z=np.dot(W,X)+b
    A=sigmoid(Z)
    cost=-(np.sum(y_train*np.log(A)+(1-y_train)*np.log(1-A))/m+(lamda/(2*m))*(np.sum(W**2)))/m
    dZ=A-y_train
    db=np.sum(dZ,axis=1,keepdims=True)/m
    dW=np.dot(dZ,X.T)/m
    return cost,dW,db

In [16]:
print(cost_fn(X,W,b,m,y_train,100))

(0.00013971911114845988, array([[0.18681088, 0.18436532, 0.03488718, 0.01838372, 0.28696606,
        0.22836871, 0.15519414, 0.2560153 , 0.01539394, 0.25939263,
        0.06774407, 0.0581751 , 0.0665317 ]]), array([[0.4518435]]))


In [17]:
def descent(X,W,b,m,y_train,itr,lr,lamda,print_cost=False):
    for i in range(itr):
        cost,dW,db=cost_fn(X,W,b,m,y_train,lamda)
        if print_cost and i%500==0:
            print(i,cost)
        W=W*(1-(lr*lamda)/m)-lr*dW
        b=b-lr*db

In [18]:
descent(X,W,b,m,y_train,10000,1,0,True)

0 0.00013972081925854197
500 3.402769143992078e-05
1000 3.279993665318316e-05
1500 3.226913057252207e-05
2000 3.200540577762174e-05
2500 3.185890862155026e-05
3000 3.17701092138945e-05
3500 3.171263456641972e-05
4000 3.1673599454955984e-05
4500 3.164615186265514e-05
5000 3.162637054749196e-05
5500 3.161186516997359e-05
6000 3.1601099164231674e-05
6500 3.159304116399356e-05
7000 3.158697490614346e-05
7500 3.158238980413149e-05
8000 3.157891471596928e-05
8500 3.157627598319007e-05
9000 3.1574269749945315e-05
9500 3.157274305926375e-05


In [19]:
def predict(X,W,b,y_test):
    print(y_test)
    m=X.shape[1]
    Z=np.dot(W,X)+b
    A=sigmoid(Z)
    print(A)
    predict=np.zeros(m)
    t=f=0
    for i in range(m):
        if(A[0][i]>0.5):
            predict[i]=1
        if(predict[i]==y_test[i]):
            t+=1
        else:
            f+=1
    print(predict)
    print(t,f)
    return t,f

In [20]:
t,f=predict(X_eval,W,b,y_eval)
print(W)
print("accuracy:",(t*100)/(t+f),"%")

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0.49897187 0.50354945 0.5053657  0.50269884 0.50140118 0.50174621
  0.50582868 0.50424791 0.50553958 0.50280926 0.50164122 0.50362652
  0.50415012 0.50191159 0.50412925 0.50214719 0.50418909 0.50504206
  0.5027084  0.50450714 0.49950761 0.50330118 0.50349699 0.50161611
  0.5030703  0.5062497  0.50726317 0.49708308 0.50001806 0.49938868
  0.50026119 0.50121139 0.50298124 0.50561775 0.50522753 0.50271062
  0.50364763 0.50243671 0.49897621 0.49713112 0.50605899 0.49893301
  0.50208177 0.5009225  0.50014678 0.50284033 0.50144866 0.50567295
  0.49863775 0.50015577 0.49701816 0.50385668 0