In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv
/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv


In [2]:
from sklearn.model_selection import train_test_split

In [3]:
dftrain=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv')
dftrain=dftrain.sample(frac=1)
dftrain,dfeval=train_test_split(dftrain, test_size=0.01)

In [4]:
print(dftrain.head())
print(dfeval.head())

      gender   age  hypertension  heart_disease ever_married work_type  \
4019    Male  30.0             0              0           No   Private   
347     Male  60.0             1              0          Yes   Private   
2557  Female  41.0             0              0           No   Private   
640   Female  23.0             0              0           No   Private   
1628  Female  50.0             0              0          Yes   Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
4019          Urban             113.08  41.8          Unknown       0  
347           Rural             213.37  36.0     never smoked       0  
2557          Urban              86.03  26.4     never smoked       0  
640           Urban              60.50  27.1  formerly smoked       0  
1628          Rural              76.55  29.0           smokes       0  
      gender   age  hypertension  heart_disease ever_married work_type  \
183   Female  63.0             0              0  

In [5]:
y_train=dftrain.pop('stroke')
y_eval=dfeval.pop('stroke')

In [6]:
dftrain.loc[dftrain['gender']=='Male','gender']=1
dftrain.loc[dftrain['gender']=='Female','gender']=0
dftrain.loc[dftrain['ever_married']=='Yes','ever_married']=1
dftrain.loc[dftrain['ever_married']=='No','ever_married']=0
dftrain.loc[dftrain['work_type']=='Private','work_type']=0
dftrain.loc[dftrain['work_type']=='Self-employed','work_type']=1
dftrain.loc[dftrain['work_type']=='Govt_job','work_type']=2
dftrain.loc[dftrain['work_type']=='children','work_type']=3
dftrain.loc[dftrain['Residence_type']=='Urban','Residence_type']=1
dftrain.loc[dftrain['Residence_type']=='Rural','Residence_type']=0
dftrain.loc[dftrain['smoking_status']=='formerly smoked','smoking_status']=0
dftrain.loc[dftrain['smoking_status']=='never smoked','smoking_status']=1
dftrain.loc[dftrain['smoking_status']=='smokes','smoking_status']=2
dftrain.loc[dftrain['smoking_status']=='Unknown','smoking_status']=3
dftrain['age']=dftrain['age']/100
dftrain['avg_glucose_level']=dftrain['avg_glucose_level']/300
dftrain['bmi']=dftrain['bmi']/50
dftrain['work_type']=dftrain['work_type']/3
dftrain['smoking_status']=dftrain['smoking_status']/3
dfeval.loc[dfeval['gender']=='Male','gender']=1
dfeval.loc[dfeval['gender']=='Female','gender']=0
dfeval.loc[dfeval['ever_married']=='Yes','ever_married']=1
dfeval.loc[dfeval['ever_married']=='No','ever_married']=0
dfeval.loc[dfeval['work_type']=='Private','work_type']=0
dfeval.loc[dfeval['work_type']=='Self-employed','work_type']=1
dfeval.loc[dfeval['work_type']=='Govt_job','work_type']=2
dfeval.loc[dfeval['work_type']=='children','work_type']=3
dfeval.loc[dfeval['Residence_type']=='Urban','Residence_type']=1
dfeval.loc[dfeval['Residence_type']=='Rural','Residence_type']=0
dfeval.loc[dfeval['smoking_status']=='formerly smoked','smoking_status']=0
dfeval.loc[dfeval['smoking_status']=='never smoked','smoking_status']=1
dfeval.loc[dfeval['smoking_status']=='smokes','smoking_status']=2
dfeval.loc[dfeval['smoking_status']=='Unknown','smoking_status']=3
dfeval['age']=dfeval['age']/100
dfeval['avg_glucose_level']=dfeval['avg_glucose_level']/300
dfeval['bmi']=dfeval['bmi']/50
dfeval['work_type']=dfeval['work_type']/3
dfeval['smoking_status']=dfeval['smoking_status']/3

In [7]:
print(dftrain.head(50))
print(dfeval.head(50))

     gender   age  hypertension  heart_disease ever_married work_type  \
4019      1  0.30             0              0            0       0.0   
347       1  0.60             1              0            1       0.0   
2557      0  0.41             0              0            0       0.0   
640       0  0.23             0              0            0       0.0   
1628      0  0.50             0              0            1       0.0   
1767      1  0.57             0              1            1  0.333333   
2081      0  0.55             0              0            1       0.0   
3287      1  0.40             0              0            0  0.666667   
3221      0  0.69             1              0            1  0.333333   
4029      0  0.79             0              0            1  0.333333   
1564      1  0.35             0              0            1       0.0   
1898      0  0.03             0              0            0       1.0   
2304      0  0.52             0              0     

In [8]:
train=dftrain.to_numpy()
evaluate=dfeval.to_numpy()
y_train=y_train.to_numpy()
y_eval=y_eval.to_numpy()

In [9]:
print(train)

[[1 0.3 0 ... 0.37693333333333334 0.836 1.0]
 [1 0.6 1 ... 0.7112333333333334 0.72 0.3333333333333333]
 [0 0.41 0 ... 0.28676666666666667 0.528 0.3333333333333333]
 ...
 [0 0.44 0 ... 0.7196666666666667 0.836 0.6666666666666666]
 [0 0.04 0 ... 0.31083333333333335 0.332 1.0]
 [1 0.66 0 ... 0.5038666666666667 0.55 0.0]]


In [10]:
X=train.T
X=np.array(X,dtype=np.float64)
X_eval=evaluate.T
X_eval=np.array(X_eval,dtype=np.float64)

In [11]:
m=X.shape[1]
n_x=X.shape[0]
n_h=10

In [12]:
print(m)

4931


In [13]:
W1=np.random.randn(n_h,n_x)*0.01
b1=np.zeros((n_h,1))
W2=np.random.randn(1,n_h)*0.01
b2=np.zeros((1,1))

In [14]:
print(W1)
print(b1)

[[ 2.08759154e-02  2.57174033e-03  2.57388353e-03 -1.16227372e-02
   3.77365598e-03 -1.52381948e-02 -1.54004244e-02  4.48243872e-03
  -1.17426010e-02  1.19171710e-02]
 [-1.26791636e-02  3.38503608e-04 -1.88375651e-02  1.52328096e-02
  -3.65965268e-03  1.89618557e-02 -1.05918880e-02 -7.98813097e-03
   1.42405640e-02  1.11630336e-02]
 [ 1.46520328e-02  9.52523731e-03 -3.10364959e-03 -1.19599203e-02
   4.26531373e-03 -2.29598564e-03 -1.55822747e-02 -1.80309177e-03
   8.27524167e-03  1.76290305e-03]
 [-4.12611061e-03  8.73205919e-03 -7.58424697e-03 -1.09931728e-02
  -8.47998899e-03 -6.46655471e-03 -2.00790821e-02  1.23777526e-02
  -9.51221548e-03  1.45538658e-02]
 [ 7.89281409e-03  9.45619903e-04  5.21631306e-03  1.66613594e-02
  -1.47448607e-02 -3.85552188e-04 -2.28982011e-03  8.32027671e-03
   2.47005418e-03 -2.95211781e-03]
 [ 5.76620951e-03 -4.96532864e-03 -6.40489569e-03  8.49855993e-03
   6.36512069e-03 -2.41157769e-03  4.70285986e-03 -2.94535882e-03
   4.86036267e-03  3.53107714e-03

In [15]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [16]:
def relu(z):
    return np.maximum(0,z)

In [17]:
print(relu(np.array([-1,2,5,0])))

[0 2 5 0]


In [18]:
def cost_fn(X,W1,b1,W2,b2,m,y_train):
    Z1=np.dot(W1,X)+b1
    A1=relu(Z1)
    Z2=np.dot(W2,A1)+b2
    A2=sigmoid(Z2)
    cost=-np.sum(y_train*np.log(A2)+(1-y_train)*np.log(1-A2))/m
    dZ2=A2-y_train
    db2=np.sum(dZ2,axis=1,keepdims=True)/m
    dW2=np.dot(dZ2,A1.T)/m
    dZ1=np.multiply(np.dot(W2.T,dZ2),1-np.power(A1,2))
    dW1=np.dot(dZ1,X.T)/m
    db1=np.sum(dZ1,axis=1,keepdims=True)/m
    return cost,dW1,db1,dW2,db2

In [19]:
print(cost_fn(X,W1,b1,W2,b2,m,y_train))

(0.6930963411724169, array([[ 7.85106138e-04,  7.70218612e-04,  1.46326165e-04,
         7.57122016e-05,  1.19866071e-03,  5.40858719e-04,
         9.54632682e-04,  6.49340131e-04,  1.06980025e-03,
         1.02229631e-03],
       [ 1.66275110e-03,  1.63095912e-03,  3.09887991e-04,
         1.60287931e-04,  2.53826974e-03,  1.14491352e-03,
         2.02130133e-03,  1.37493198e-03,  2.26523118e-03,
         2.16450587e-03],
       [-1.64357582e-03, -1.61240899e-03, -3.06345693e-04,
        -1.58507996e-04, -2.50931240e-03, -1.13226714e-03,
        -1.99861948e-03, -1.35938562e-03, -2.23959196e-03,
        -2.14023795e-03],
       [-1.12493176e-03, -1.10344057e-03, -2.09643762e-04,
        -1.08461666e-04, -1.71726870e-03, -7.74793490e-04,
        -1.36751827e-03, -9.30257554e-04, -1.53261494e-03,
        -1.46457680e-03],
       [-1.51966768e-03, -1.49067859e-03, -2.83205733e-04,
        -1.46498209e-04, -2.31993530e-03, -1.04669579e-03,
        -1.84741809e-03, -1.25672050e-03, -2.0704

In [20]:
def descent(X,W1,b1,W2,b2,m,y_train,itr,lr1,lr2):
    for i in range(itr):
        cost,dW1,db1,dW2,db2=cost_fn(X,W1,b1,W2,b2,m,y_train)
        print(i,cost)
        W1=W1-lr1*dW1
        b1=b1-lr1*db1
        W2=W2-lr2*dW2
        b2=b2-lr2*db2

In [21]:
descent(X,W1,b1,W2,b2,m,y_train,1000,0.1,15)

0 0.6930963411724169
1 0.3346220651864568
2 0.30019976662273395
3 0.2678922424651672
4 0.23949290324832592
5 0.21750753107550339
6 0.20397203041937942
7 0.19819067187556944
8 0.19666870060399821
9 0.19642236242036956
10 0.19639307984020118
11 0.19638901887866606
12 0.19638741822570868
13 0.1963860566547682
14 0.19638472974123083
15 0.1963834172593081
16 0.19638211845063036
17 0.19638082965171433
18 0.19637954779290706
19 0.19637827211396153
20 0.19637699871293435
21 0.19637572602722908
22 0.19637445310763513
23 0.19637317733773557
24 0.19637189626677484
25 0.19637060879716986
26 0.19636931503513783
27 0.19636801396718026
28 0.19636670439516635
29 0.1963653827284118
30 0.19636404525541387
31 0.1963626874292544
32 0.19636130717582698
33 0.19635990405340997
34 0.1963584761721912
35 0.19635702075444927
36 0.19635553624175436
37 0.19635401835023789
38 0.19635247059999886
39 0.19635088661888636
40 0.1963492617420594
41 0.19634759301282756
42 0.19634588140466824
43 0.19634411934138707
44 0.19

In [22]:
def predict(X,W1,b1,W2,b2,y_test):
    print(y_test)
    m=X.shape[1]
    Z1=np.dot(W1,X)+b1
    A1=relu(Z1)
    Z2=np.dot(W2,A1)+b2
    A2=sigmoid(Z2)
    print(A2)
    predict=np.zeros(m)
    t=f=0
    for i in range(m):
        if(A2[0][i]>0.5001):
            predict[i]=1
        if(predict[i]==y_test[i]):
            t+=1
        else:
            f+=1
    print(predict)
    print(t,f)
    return t,f

In [23]:
t,f=predict(X_eval,W1,b1,W2,b2,y_eval)
print("accuracy:",(t*100)/(t+f),"%")

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0]
[[0.50000214 0.49993884 0.50000391 0.49996389 0.49995366 0.50000122
  0.49997661 0.49998479 0.49995865 0.50000511 0.49995334 0.49996898
  0.50000689 0.4999489  0.49995052 0.4999528  0.49998829 0.4999744
  0.4999724  0.49997839 0.50003698 0.49995212 0.49990917 0.49997619
  0.49994075 0.49997243 0.49995714 0.49996245 0.49995804 0.5000147
  0.49994694 0.49998764 0.49994876 0.49991413 0.49998495 0.49998735
  0.49995667 0.49995639 0.49995443 0.49994416 0.49997459 0.49994168
  0.50001799 0.49995687 0.49995589 0.49995882 0.50003674 0.49997593
  0.50000937 0.49998922]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
45 5
accuracy: 90.0 %
