In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv
/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv


In [2]:
dftrain=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv')
dfeval=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv')

In [3]:
print(dftrain.head())

   gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1  


In [4]:
y_train=dftrain.pop('stroke')
y_eval=dfeval.pop('stroke')

In [5]:
dftrain.loc[dftrain['gender']=='Male','gender']=1
dftrain.loc[dftrain['gender']=='Female','gender']=0
dftrain.loc[dftrain['ever_married']=='Yes','ever_married']=1
dftrain.loc[dftrain['ever_married']=='No','ever_married']=0
dftrain.loc[dftrain['work_type']=='Private','work_type']=0
dftrain.loc[dftrain['work_type']=='Self-employed','work_type']=1
dftrain.loc[dftrain['work_type']=='Govt_job','work_type']=2
dftrain.loc[dftrain['work_type']=='children','work_type']=3
dftrain.loc[dftrain['Residence_type']=='Urban','Residence_type']=1
dftrain.loc[dftrain['Residence_type']=='Rural','Residence_type']=0
dftrain.loc[dftrain['smoking_status']=='formerly smoked','smoking_status']=0
dftrain.loc[dftrain['smoking_status']=='never smoked','smoking_status']=1
dftrain.loc[dftrain['smoking_status']=='smokes','smoking_status']=2
dftrain.loc[dftrain['smoking_status']=='Unknown','smoking_status']=3
dftrain['age']=dftrain['age']/100
dftrain['avg_glucose_level']=dftrain['avg_glucose_level']/300
dftrain['bmi']=dftrain['bmi']/50
dfeval.loc[dfeval['gender']=='Male','gender']=1
dfeval.loc[dfeval['gender']=='Female','gender']=0
dfeval.loc[dfeval['ever_married']=='Yes','ever_married']=1
dfeval.loc[dfeval['ever_married']=='No','ever_married']=0
dfeval.loc[dfeval['work_type']=='Private','work_type']=0
dfeval.loc[dfeval['work_type']=='Self-employed','work_type']=1
dfeval.loc[dfeval['work_type']=='Govt_job','work_type']=2
dfeval.loc[dfeval['work_type']=='children','work_type']=3
dfeval.loc[dfeval['Residence_type']=='Urban','Residence_type']=1
dfeval.loc[dfeval['Residence_type']=='Rural','Residence_type']=0
dfeval.loc[dfeval['smoking_status']=='formerly smoked','smoking_status']=0
dfeval.loc[dfeval['smoking_status']=='never smoked','smoking_status']=1
dfeval.loc[dfeval['smoking_status']=='smokes','smoking_status']=2
dfeval.loc[dfeval['smoking_status']=='Unknown','smoking_status']=3
dfeval['age']=dfeval['age']/100
dfeval['avg_glucose_level']=dfeval['avg_glucose_level']/300
dfeval['bmi']=dfeval['bmi']/50

In [6]:
print(dftrain.head(50))
print(dfeval.head(50))

   gender   age  hypertension  heart_disease ever_married work_type  \
0       1  0.67             0              1            1         0   
1       1  0.80             0              1            1         0   
2       0  0.49             0              0            1         0   
3       0  0.79             1              0            1         1   
4       1  0.81             0              0            1         0   
5       1  0.74             1              1            1         0   
6       0  0.69             0              0            0         0   
7       0  0.78             0              0            1         0   
8       0  0.81             1              0            1         0   
9       0  0.61             0              1            1         2   
10      0  0.54             0              0            1         0   
11      0  0.79             0              1            1         0   
12      0  0.50             1              0            1         1   
13    

In [7]:
train=dftrain.to_numpy()
evaluate=dfeval.to_numpy()
y_train=y_train.to_numpy()
y_eval=y_eval.to_numpy()

In [8]:
print(train)

[[1 0.67 0 ... 0.7623 0.732 0]
 [1 0.8 0 ... 0.3530666666666667 0.65 1]
 [0 0.49 0 ... 0.5707666666666666 0.688 2]
 ...
 [0 0.45 1 ... 0.3167333333333333 0.636 2]
 [1 0.4 0 ... 0.2798 0.6 2]
 [0 0.8 1 ... 0.2791666666666667 0.5820000000000001 1]]


In [9]:
X=train.T
X=np.array(X,dtype=np.float64)
X_eval=evaluate.T
X_eval=np.array(X_eval,dtype=np.float64)

In [10]:
m=X.shape[1]
n_x=X.shape[0]

In [11]:
print(m)

4981


In [12]:
W1=np.random.randn(1,n_x)
b1=np.zeros((1,1))

In [13]:
print(W1)
print(b1)

[[ 0.74380355 -0.20578246  0.44059151  1.23906399  1.46180777  0.56398365
   0.19493716  1.07498596 -1.5825222   1.09484688]]
[[0.]]


In [14]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [15]:
def cost_fn(X,W,b,m,y_train):
    Z=np.dot(W,X)+b
    a=sigmoid(Z)
    cost=-np.sum(y_train*np.log(a)+(1-y_train)*np.log(1-a))/m
    dZ=a-y_train
    db=np.sum(dZ)/m
    dW=np.dot(X,dZ.T)/m
    return cost,dW,db

In [16]:
print(cost_fn(X,W1,b1,m,y_train))

(3.0240779233818946, array([[0.36955801],
       [0.35934078],
       [0.07651582],
       [0.04420369],
       [0.56448721],
       [0.76746946],
       [0.43696285],
       [0.29968206],
       [0.48285345],
       [1.44879235]]), 0.8552380559946816)


In [17]:
def descent(X,W,b,m,y_train,itr=100,lr=0.001):
    for i in range(itr):
        cost,dW,db=cost_fn(X,W,b,m,y_train)
        print(i,cost)
        W=W-lr*dW.T
        b=b-lr*db

In [18]:
descent(X,W1,b1,m,y_train,1000,5)

0 3.0240779233818946
1 1.014951547303961
2 0.9492803209309111
3 0.883620609536462
4 0.8179839464933228
5 0.7523946351749389
6 0.6869050556902205
7 0.6216303189445267
8 0.5568266388924257
9 0.49306294584690596
10 0.43155833206958916
11 0.37466878807735854
12 0.32602097119025014
13 0.28910559490940707
14 0.2643457419763096
15 0.2481677678807188
16 0.23628052804886981
17 0.22650813668387867
18 0.21824974908703296
19 0.2113338941513257
20 0.20562783558647416
21 0.20098183902496775
22 0.19723630589639893
23 0.19423581512480678
24 0.19183974723272912
25 0.1899274822236849
26 0.18839912344260223
27 0.18717360892190993
28 0.18618582726881838
29 0.18538372315839222
30 0.1847258130858958
31 0.18417918466323904
32 0.18371790186234083
33 0.18332170941185424
34 0.18297495322388052
35 0.18266566708366544
36 0.18238480006472507
37 0.18212557099399634
38 0.18188293934710048
39 0.18165318088610655
40 0.18143355450879964
41 0.1812220457835353
42 0.18101717288342087
43 0.18081784186788097
44 0.1806232400

In [19]:
def predict(X,W,b,y_test):
    print(W.shape,X.shape,b)
    print(y_test)
    m=X.shape[1]
    z=np.dot(W,X)+b
    a=sigmoid(z)
    predict=np.zeros(m)
    t=f=0
    for i in range(m):
        if(a[0][i]>0.5):
            predict[i]=1
        if(predict[i]==y_test[i]):
            t+=1
        else:
            f+=1
    print(predict)
    print(t,f)

In [20]:
predict(X_eval,W1,b1,y_eval)

(1, 10) (10, 201) [[0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 