In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv
/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv


In [2]:
dftrain=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_data.csv')
dfeval=pd.read_csv('/kaggle/input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv')

In [3]:
print(dftrain.head())

   gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1  


In [4]:
y_train=dftrain.pop('stroke')
y_eval=dfeval.pop('stroke')

In [5]:
dftrain.loc[dftrain['gender']=='Male','gender']=1
dftrain.loc[dftrain['gender']=='Female','gender']=0
dftrain.loc[dftrain['ever_married']=='Yes','ever_married']=1
dftrain.loc[dftrain['ever_married']=='No','ever_married']=0
dftrain.loc[dftrain['work_type']=='Private','work_type']=0
dftrain.loc[dftrain['work_type']=='Self-employed','work_type']=1
dftrain.loc[dftrain['work_type']=='Govt_job','work_type']=2
dftrain.loc[dftrain['work_type']=='children','work_type']=3
dftrain.loc[dftrain['Residence_type']=='Urban','Residence_type']=1
dftrain.loc[dftrain['Residence_type']=='Rural','Residence_type']=0
dftrain.loc[dftrain['smoking_status']=='formerly smoked','smoking_status']=0
dftrain.loc[dftrain['smoking_status']=='never smoked','smoking_status']=1
dftrain.loc[dftrain['smoking_status']=='smokes','smoking_status']=2
dftrain.loc[dftrain['smoking_status']=='Unknown','smoking_status']=3
dftrain['age']=dftrain['age']/100
dftrain['avg_glucose_level']=dftrain['avg_glucose_level']/300
dftrain['bmi']=dftrain['bmi']/50
dfeval.loc[dfeval['gender']=='Male','gender']=1
dfeval.loc[dfeval['gender']=='Female','gender']=0
dfeval.loc[dfeval['ever_married']=='Yes','ever_married']=1
dfeval.loc[dfeval['ever_married']=='No','ever_married']=0
dfeval.loc[dfeval['work_type']=='Private','work_type']=0
dfeval.loc[dfeval['work_type']=='Self-employed','work_type']=1
dfeval.loc[dfeval['work_type']=='Govt_job','work_type']=2
dfeval.loc[dfeval['work_type']=='children','work_type']=3
dfeval.loc[dfeval['Residence_type']=='Urban','Residence_type']=1
dfeval.loc[dfeval['Residence_type']=='Rural','Residence_type']=0
dfeval.loc[dfeval['smoking_status']=='formerly smoked','smoking_status']=0
dfeval.loc[dfeval['smoking_status']=='never smoked','smoking_status']=1
dfeval.loc[dfeval['smoking_status']=='smokes','smoking_status']=2
dfeval.loc[dfeval['smoking_status']=='Unknown','smoking_status']=3
dfeval['age']=dfeval['age']/100
dfeval['avg_glucose_level']=dfeval['avg_glucose_level']/300
dfeval['bmi']=dfeval['bmi']/50

In [6]:
print(dftrain.head(50))
print(dfeval.head(50))

   gender   age  hypertension  heart_disease ever_married work_type  \
0       1  0.67             0              1            1         0   
1       1  0.80             0              1            1         0   
2       0  0.49             0              0            1         0   
3       0  0.79             1              0            1         1   
4       1  0.81             0              0            1         0   
5       1  0.74             1              1            1         0   
6       0  0.69             0              0            0         0   
7       0  0.78             0              0            1         0   
8       0  0.81             1              0            1         0   
9       0  0.61             0              1            1         2   
10      0  0.54             0              0            1         0   
11      0  0.79             0              1            1         0   
12      0  0.50             1              0            1         1   
13    

In [7]:
train=dftrain.to_numpy()
evaluate=dfeval.to_numpy()
y_train=y_train.to_numpy()
y_eval=y_eval.to_numpy()

In [8]:
print(train)

[[1 0.67 0 ... 0.7623 0.732 0]
 [1 0.8 0 ... 0.3530666666666667 0.65 1]
 [0 0.49 0 ... 0.5707666666666666 0.688 2]
 ...
 [0 0.45 1 ... 0.3167333333333333 0.636 2]
 [1 0.4 0 ... 0.2798 0.6 2]
 [0 0.8 1 ... 0.2791666666666667 0.5820000000000001 1]]
